export const API_CONFIG = {
  // BASE_URL: "https://thesis-h7aqe0buf9hncygr.ukwest-01.azurewebsites.net/api",
  BASE_URL: "https://localhost:5070/api",
  ENDPOINTS: {
    AUTH: {
      LOGIN: "/auth/login",
      REGISTER: "/auth/register",
      LOGOUT: "/auth/logout",
      ME: "/auth/me",
      REFRESH_TOKEN: "/auth/refresh-token",
      FORGOT_PASSWORD: "/auth/forgot-password",
      RESET_PASSWORD: "/auth/reset-password",
    },
    USER: {
      LIST: "/users",
      DETAIL: (id: number) => `/users/${id}`,
      UPDATE: "/users/update",
      BY_ID: (id: number) => `/users/${id}`,
    },
    PROFILE: {
      CHANGE_PASSWORD: "/users/change-password",
      UPLOAD_AVATAR: "/users/upload-avatar",
    },
    THESIS: {
      LIST: "/theses",
      MY_THESES: "/theses/my-thesis",
      DETAIL: (id: number) => `/theses/${id}`,
      CREATE: "/theses",
      UPDATE: (id: number) => `/theses/${id}`,
      DELETE: (id: number) => `/theses/${id}`,
      DOCUMENTS: (thesisId: string) => `/theses/${thesisId}/documents`,
      UPDATE_STATUS: (id: number, status: string) =>
        `/theses/${id}/status?status=${status}`,
    },
    TEACHER: {
      LIST: "/users/lectures",
      INTERNAL_LECTURERS: "/users/internal-lecturers",
      EXTERNAL_LECTURERS: "/users/external-lecturers",
      DETAIL: (id: string) => `/teachers/${id}`,
    },
    STUDENT: {
      LIST: "/users/students",
    },
    DASHBOARD: {
      STATS: "/dashboard/stats",
      RECENT_THESES: "/dashboard/recent-theses",
      ACTIVITIES: "/dashboard/activities",
      USER_STATS: "/dashboard/user-stats",
      ASSIGNED_STUDENTS: "/dashboard/assigned-students",
      THESIS_PROGRESS: "/dashboard/thesis-progress",
    },
    MAJOR: {
      LIST: "/majors",
      DETAIL: (id: number) => `/majors/${id}`,
      CREATE: "/majors",
      UPDATE: (id: number) => `/majors/${id}`,
      DELETE: (id: number) => `/majors/${id}`,
    },
    TASK: {
      LIST: "/tasks",
      DETAIL: (id: number) => `/tasks/${id}/view`,
      CREATE: "/tasks",
      UPDATE: (id: number) => `/tasks/${id}/update`,
      DELETE: (id: number) => `/tasks/${id}`,
      UPDATE_STATUS: (id: number) => `/tasks/${id}/status`,
      UPLOAD_FILE: (id: number) => `/tasks/${id}/file`,
      DOWNLOAD_FILE: (id: number) => `/tasks/${id}/file`,
      LIST_BY_REQUEST: (id: number) => `/tasks/${id}`,
    },
    REQUEST: {
      LIST: "/requests",
      DETAIL: (id: number) => `/requests/${id}`,
      CREATE: "/requests/create",
      UPDATE: (id: number) => `/requests/${id}`,
      DELETE: (id: number) => `/requests/${id}`,
      CURRENT: "/requests/current",
      ALL: "/requests/all",
      UPDATE_STATUS: (id: number) => `/requests/${id}/status`,
    },
    MATERIAL: {
      LIST_BY_THESIS: (thesisId: number) => `/material/${thesisId}/get-all`,
      CREATE: "/material",
      DELETE: (id: number) => `/material/${id}`,
    },
    FEEDBACK: {
      CREATE: "/feedback",
      GET_BY_TASK_ID: (taskId: number) => `/feedback/${taskId}/get-all`,
    }
  },
} as const;
